Traceback (most recent call last):
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
% matplotlib inline

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

county_inc = pd.read_csv('data/county_incomes.csv')
county_pop = pd.read_csv('data/county_population.csv')
city_inc = pd.read_csv('data/city_incomes.csv')

calif = (
    county_inc
    .merge(county_pop)
    .merge(city_inc, on='County', suffixes=['_County', '_City'])
    .sort_index(axis=1)
)
------------------


UsageError: Line magic function `%` not found.

