Traceback (most recent call last):
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/afraenkel/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
D = prices.set_index('Plan Type').to_dict()
purchases['Price'] = purchases.apply(lambda x:D.get(x['Plan Type']))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-20-16b159340c77>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mD[0m [0;34m=[0m [0mprices[0m[0;34m.[0m[0mset_index[0m[0;34m([0m[0;34m'Plan Type'[0m[0;34m)[0m[0;34m.[0m[0mto_dict[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mpurchases[0m[0;34m[[0m[0;34m'Price'[0m[0;34m][0m [0;34m=[0m [0mpurchases[0m[0;34m.[0m[0mapply[0m[0;34m([0m[0;32mlambda[0m [0mx[0m[0;34m:[0m[0mD[0m[0;34m.[0m[0mget[0m[0;34m([0m[0mx[0m[0;34m[[0m[0;34m'Plan Type'[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'prices' is not defined
NameError: name 'prices' is not defined

